---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistant-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.mysql.volumeSize }}Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mysql-data"
