---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-persistant-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.volumeSize }}Gi
      