---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
  - port: {{ .Values.mysql.port }}
    targetPort: {{ .Values.mysql.port }}
  selector:
    app: {{ .Release.Name }}
  clusterIP: None
